version: '3.8'

services:
  ghl_system:
    build: .
    container_name: ghl_system_app
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./storage:/app/storage
    env_file:
      - .env